%%{init: {"flowchart": {"nodeSpacing": 20, "rankSpacing": 40}}}%%
flowchart TB
  _legacy["_legacy/"]
  _legacy["_legacy/"] --> _legacy_backups["_legacy/backups/"]
  _legacy["_legacy/"] --> _legacy_components["_legacy/components/"]
  _legacy["_legacy/"] --> _legacy_tests["_legacy/tests/"]
  _legacy["_legacy/"] --> _legacy_utilities["_legacy/utilities/"]
